In [121]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [122]:
# Charger les donnÃ©es
df = pd.read_csv("automobile_data.csv", sep=";")
df

,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
200,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [123]:
df.dtypes

body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [124]:
# SÃ©lectionner uniquement les colonnes numÃ©riques
df_num = df.select_dtypes(exclude="object")

# VÃ©rifier si "price" est bien dans df_num, sinon l'extraire de df
if "price" in df_num.columns:
    y = df_num["price"]
    X = df_num.drop(columns=["price"])
else:
    y = df["price"]
    X = df_num

# Diviser les donnÃ©es en train et test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(160, 9) (41, 9) (160,) (41,)

In [125]:
df.dtypes

body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [126]:
df.describe().round(2)

,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg,price
count,201.00,201.00,201.00,201.00,201.00,201.00,201.00,201.00,201.00,201.00
mean,98.80,174.20,65.89,53.77,2555.67,126.88,10.16,25.18,30.69,13207.13
std,6.07,12.32,2.10,2.45,517.30,41.55,4.00,6.42,6.82,7947.07
min,86.60,141.10,60.30,47.80,1488.00,61.00,7.00,13.00,16.00,5118.00
25%,94.50,166.80,64.10,52.00,2169.00,98.00,8.60,19.00,25.00,7775.00
50%,97.00,173.20,65.50,54.10,2414.00,120.00,9.00,24.00,30.00,10295.00
75%,102.40,183.50,66.60,55.50,2926.00,141.00,9.40,30.00,34.00,16500.00
max,120.90,208.10,72.00,59.80,4066.00,326.00,23.00,49.00,54.00,45400.00

In [127]:
# ModÃ¨le de rÃ©gression linÃ©aire multiple

lr = LinearRegression()
lr.fit(X_train, y_train)

# PrÃ©diction
y_pred = lr.predict(X_test)

# Ã‰valuation du modÃ¨le
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 7960837.279830839

In [128]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(160, 9) (41, 9) (160,) (41,)

In [129]:
# DÃ©finition de la graine (seed)
seed = 123  

# ModÃ¨le de forÃªt alÃ©atoire
rf = RandomForestRegressor(random_state=seed)
rf.fit(X_train, y_train)

# PrÃ©diction
y_pred_rf = rf.predict(X_test)

# Ã‰valuation du modÃ¨le
mse_rf = mean_squared_error(y_test, y_pred_rf)
print("Mean Squared Error (Random Forest):", mse_rf)

Mean Squared Error (Random Forest): 2327253.8478405145

In [130]:
mse_rf < mse # On retient le modÃ¨le rf

True

In [131]:
# Sauvegarder le modÃ¨le

In [132]:
import joblib

joblib.dump(rf , "final_model.joblib")

['final_model.joblib']